import  { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import  ReactQueryProvider from '../lib/react-query';
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children  }) {
  return (
    
       <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <Header/>
                <main>{children}</main>
            <Footer/>
          </ReactQueryProvider>
          
        </body>
       </html>

    
   
  );
}
