"use client";

import { useEffect } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import  ReactQueryProvider from '../lib/react-query';
import Header from "@/components/header";
import Footer from "@/components/footer";
import { BaseUrl } from "@/lib/utils";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children  }) {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const token = localStorage.getItem("authToken");
    if (token) {
      fetchUser(token);
    }
  }, []);

  const fetchUser = async (token) => {
    const response = await fetch(`${BaseUrl()}/api/users/me`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (response.ok) {
      const data = await response.json();
      setUser(data);
    } else {
      localStorage.removeItem("authToken");
    }
  };

  const handleLogin = (userData) => {
    setUser(userData);
  };

  const handleLogout = () => {
    localStorage.removeItem("authToken");
    setUser(null);
  };
  return (
    
       <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
          {/* <Header user={user} onLogout={handleLogout} /> */}
                <main>{children}</main>
            <Footer/>
          </ReactQueryProvider>
          
        </body>
       </html>

    
   
  );
}
